"Nothing is impossible, the word itself says I'm possible - Audrey Hepburn"
"The best preparation for tomorrow is doing your best today - H. Jackson Brown, Jr."
"Change your thoughts and you change your world - Norman Vincent Peale"
"It might be stormy now, but it can't rain forever - Anonymous"
"Hardships often prepare ordinary people for an extraordinary destiny - C.S. Lewis"